apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: models-pvc
  namespace: {{ .Values.global.namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.persistence.models.storageClass }}
  resources:
    requests:
      storage: {{ .Values.persistence.models.size }}
