apiVersion: v1
kind: Namespace
metadata:
  name: securecloud
  labels:
    istio-injection: enabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: siem
  labels:
    istio-injection: enabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: ml
  labels:
    istio-injection: enabled
