apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: securecloud-mtls
  namespace: securecloud
spec:
  host: "*.securecloud.svc.cluster.local"
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: siem-mtls
  namespace: siem
spec:
  host: "*.siem.svc.cluster.local"
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: ml-mtls
  namespace: ml
spec:
  host: "*.ml.svc.cluster.local"
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
