apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
  namespace: apps
  labels:
    app: frontend
    component: bkash-demo
data:
  PAYMENT_API_URL: "http://payment-api.apps.svc.cluster.local:8000"
  PORT: "5000"
  LOG_LEVEL: "INFO"
  FLASK_ENV: "production"
