apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-api
  namespace: apps
  labels:
    app: payment-api
    component: bkash-demo
    version: v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: payment-api
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: payment-api
        component: bkash-demo
        version: v1
    spec:
      automountServiceAccountToken: false
      securityContext:
        runAsNonRoot: true
        runAsUser: 1001
        runAsGroup: 1001
        fsGroup: 1001
      # Wait for user-db to be reachable before starting
      initContainers:
        - name: wait-for-db
          image: busybox:1.36
          command:
            - sh
            - -c
            - |
              until nc -z user-db.apps.svc.cluster.local 5432; do
                echo "Waiting for PostgreSQL…"
                sleep 3
              done
              echo "PostgreSQL is reachable"
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            runAsUser: 1001
            capabilities:
              drop: ["ALL"]
      containers:
        - name: payment-api
          image: securecloud/bkash-payment-api:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
              name: http
          envFrom:
            - configMapRef:
                name: payment-api-config
          env:
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: payment-api-secret
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: payment-api-secret
                  key: DB_PASSWORD
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop: ["ALL"]
          volumeMounts:
            - name: tmp
              mountPath: /tmp
          resources:
            requests:
              cpu: "150m"
              memory: "128Mi"
            limits:
              cpu: "400m"
              memory: "256Mi"
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 25
            periodSeconds: 15
      volumes:
        - name: tmp
          emptyDir: {}
